# docker/Dockerfile

FROM python:3.8-slim

WORKDIR /app

COPY ../ .  
#copia tudo da raiz do projeto para /app no container

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
